# Generated by Django 6.0.2 on 2026-02-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('sport', 'Спорт'), ('esport', 'Киберспорт')], max_length=20)),
                ('discipline', models.CharField(blank=True, choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('cs2', 'CS2'), ('dota2', 'Dota 2'), ('pubg', 'PUBG')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('country', models.CharField(default='Kazakhstan', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['kind', 'discipline'], name='teams_team_kind_0c73dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('position', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='teams_playe_name_7cf61e_idx')],
            },
        ),
    ]
