# Generated by Django 4.2.11 on 2026-02-27 19:38

from django.db import migrations, models


def mark_synced_teams_as_not_manual(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    Team.objects.filter(source_updated_at__isnull=False).update(is_manual=False)


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_city_team_source_updated_at_team_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_manual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_manual', 'is_active'], name='teams_team_is_manu_8f46bf_idx'),
        ),
        migrations.RunPython(mark_synced_teams_as_not_manual, migrations.RunPython.noop),
    ]
