# Generated by Django 4.2.11 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_team_is_active_team_is_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="source_url",
            field=models.URLField(blank=True),
        ),
    ]
