# Generated by Django 4.2.11 on 2026-03-02 14:49

from django.db import migrations, models


def mark_demo_teams_as_examples(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    Team.objects.filter(name__startswith='Demo:').update(is_example=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_mark_all_teams_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='discipline',
            field=models.CharField(blank=True, choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('volleyball', 'Волейбол'), ('boxing', 'Бокс'), ('wrestling', 'Борьба'), ('hockey', 'Хоккей'), ('futsal', 'Футзал'), ('tennis', 'Теннис'), ('cs2', 'CS2'), ('dota2', 'Dota 2'), ('pubg', 'PUBG')], max_length=20),
        ),
        migrations.RunPython(mark_demo_teams_as_examples, noop),
    ]
