# Generated by Django 4.2.11 on 2026-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discipline',
            field=models.CharField(blank=True, choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('athletics', 'Легкая атлетика'), ('volleyball', 'Волейбол'), ('boxing', 'Бокс'), ('wrestling', 'Борьба'), ('hockey', 'Хоккей'), ('futsal', 'Футзал'), ('tennis', 'Теннис'), ('cs2', 'CS2'), ('dota2', 'Dota 2'), ('pubg', 'PUBG')], max_length=20),
        ),
    ]
