# Generated by Django 6.0.2 on 2026-02-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('stage', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('live', 'Идет'), ('finished', 'Завершен')], default='scheduled', max_length=20)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='teams.team')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.PositiveIntegerField()),
                ('score_b', models.PositiveIntegerField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tournaments.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='teams.team')),
            ],
            options={
                'ordering': ('-match__datetime',),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('sport', 'Спорт'), ('esport', 'Киберспорт')], max_length=20)),
                ('discipline', models.CharField(blank=True, choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('cs2', 'CS2'), ('dota2', 'Dota 2'), ('pubg', 'PUBG')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['kind', 'discipline', 'start_date'], name='tournaments_kind_211054_idx')],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'datetime'], name='tournaments_tournam_9f6d26_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='tournaments_status_7d43fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('team_a', models.F('team_b')), _negated=True), name='match_team_a_not_equal_team_b'),
        ),
    ]
