# Generated by Django 4.2.11 on 2026-03-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_is_example_alter_team_discipline'),
        ('tournaments', '0005_match_manual_fields_and_seed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-start_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ('-match__start_datetime',)},
        ),
        migrations.RenameIndex(
            model_name='tournament',
            new_name='tournaments_status_4964a3_idx',
            old_name='tournaments_status_example_idx',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_away', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='discipline',
            field=models.CharField(blank=True, choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('volleyball', 'Волейбол'), ('boxing', 'Бокс'), ('wrestling', 'Борьба'), ('hockey', 'Хоккей'), ('futsal', 'Футзал'), ('tennis', 'Теннис'), ('cs2', 'CS2'), ('dota2', 'Dota 2'), ('pubg', 'PUBG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_home', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='discipline',
            field=models.CharField(blank=True, choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('volleyball', 'Волейбол'), ('boxing', 'Бокс'), ('wrestling', 'Борьба'), ('hockey', 'Хоккей'), ('futsal', 'Футзал'), ('tennis', 'Теннис'), ('cs2', 'CS2'), ('dota2', 'Dota 2'), ('pubg', 'PUBG')], max_length=20),
        ),
    ]
