from datetime import datetime, timezone

from .types import MatchEntity, TeamEntity, TournamentEntity

NOW = datetime.now(timezone.utc)

FALLBACK_TEAMS = [
    TeamEntity(
        id="football-fc-astana",
        name="FC Astana",
        discipline="football",
        country="Kazakhstan",
        city="Astana",
        source_url="https://kpl.kz/",
        updated_at=NOW,
    ),
    TeamEntity(
        id="football-fc-kairat",
        name="FC Kairat",
        discipline="football",
        country="Kazakhstan",
        city="Almaty",
        source_url="https://kpl.kz/",
        updated_at=NOW,
    ),
    TeamEntity(
        id="football-fc-ordabasy",
        name="FC Ordabasy",
        discipline="football",
        country="Kazakhstan",
        city="Shymkent",
        source_url="https://kpl.kz/",
        updated_at=NOW,
    ),
    TeamEntity(
        id="basketball-bc-astana",
        name="BC Astana",
        discipline="basketball",
        country="Kazakhstan",
        city="Astana",
        source_url="https://astanabasket.kz/",
        updated_at=NOW,
    ),
    TeamEntity(
        id="basketball-irbis-almaty",
        name="Irbis Almaty",
        discipline="basketball",
        country="Kazakhstan",
        city="Almaty",
        source_url="https://fiba3x3.com/",
        updated_at=NOW,
    ),
    TeamEntity(
        id="cs2-avangar",
        name="AVANGAR",
        discipline="cs2",
        country="Kazakhstan",
        source_url="https://liquipedia.net/counterstrike/AVANGAR",
        updated_at=NOW,
    ),
    TeamEntity(
        id="cs2-k23",
        name="K23",
        discipline="cs2",
        country="Kazakhstan",
        source_url="https://liquipedia.net/counterstrike/K23",
        updated_at=NOW,
    ),
    TeamEntity(
        id="dota2-team-kz",
        name="Team Kazakhstan (Dota 2)",
        discipline="dota2",
        country="Kazakhstan",
        source_url="https://liquipedia.net/dota2/Kazakhstan",
        updated_at=NOW,
    ),
    TeamEntity(
        id="pubg-nomad-fire",
        name="Nomad Fire",
        discipline="pubg",
        country="Kazakhstan",
        source_url="https://liquipedia.net/pubg/Kazakhstan",
        updated_at=NOW,
    ),
]

FALLBACK_TOURNAMENTS = [
    TournamentEntity(
        id="kz-premier-football-spring",
        name="KZ Premier Football Spring",
        discipline="football",
        tier="National",
        location="Astana",
        start_date=datetime(2026, 3, 1, 12, 0, tzinfo=timezone.utc),
        end_date=datetime(2026, 4, 12, 12, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://kpl.kz/",
        updated_at=NOW,
    ),
    TournamentEntity(
        id="central-asia-dota-cup",
        name="Central Asia Dota Cup",
        discipline="dota2",
        tier="B-Tier",
        location="Shymkent",
        start_date=datetime(2026, 3, 14, 12, 0, tzinfo=timezone.utc),
        end_date=datetime(2026, 3, 29, 12, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://liquipedia.net/dota2/Main_Page",
        updated_at=NOW,
    ),
    TournamentEntity(
        id="kz-esports-league-cs2",
        name="KZ Esports League CS2",
        discipline="cs2",
        tier="Regional",
        location="Almaty",
        start_date=datetime(2026, 3, 5, 12, 0, tzinfo=timezone.utc),
        end_date=datetime(2026, 3, 30, 12, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://liquipedia.net/counterstrike/Main_Page",
        updated_at=NOW,
    ),
    TournamentEntity(
        id="pubg-continental-series",
        name="PUBG Continental Series",
        discipline="pubg",
        tier="International",
        location="Almaty",
        start_date=datetime(2026, 3, 21, 12, 0, tzinfo=timezone.utc),
        end_date=datetime(2026, 4, 6, 12, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://liquipedia.net/pubg/PUBG_Continental_Series",
        updated_at=NOW,
    ),
]

FALLBACK_MATCHES = [
    MatchEntity(
        id="m-football-astana-kairat",
        discipline="football",
        tournament_id="kz-premier-football-spring",
        team_a="FC Astana",
        team_b="FC Kairat",
        start_time=datetime(2026, 3, 16, 14, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://kpl.kz/",
        updated_at=NOW,
    ),
    MatchEntity(
        id="m-football-ordabasy-astana",
        discipline="football",
        tournament_id="kz-premier-football-spring",
        team_a="FC Ordabasy",
        team_b="FC Astana",
        start_time=datetime(2026, 3, 22, 15, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://kpl.kz/",
        updated_at=NOW,
    ),
    MatchEntity(
        id="m-cs2-avangar-k23",
        discipline="cs2",
        tournament_id="kz-esports-league-cs2",
        team_a="AVANGAR",
        team_b="K23",
        start_time=datetime(2026, 3, 28, 16, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://liquipedia.net/counterstrike/AVANGAR",
        updated_at=NOW,
    ),
    MatchEntity(
        id="m-dota-kz-open",
        discipline="dota2",
        tournament_id="central-asia-dota-cup",
        team_a="Team Kazakhstan (Dota 2)",
        team_b="Nomad Fire",
        start_time=datetime(2026, 3, 24, 14, 0, tzinfo=timezone.utc),
        status="upcoming",
        source_url="https://liquipedia.net/dota2/Kazakhstan",
        updated_at=NOW,
    ),
]

FALLBACK_SOURCES = [
    "https://kpl.kz/",
    "https://astanabasket.kz/",
    "https://liquipedia.net/counterstrike/Main_Page",
    "https://liquipedia.net/dota2/Main_Page",
    "https://liquipedia.net/pubg/Main_Page",
]
